version: '3'

services:
  client:
    build:
      context: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front:/app
    command: yarn run dev

  server:
    build:
      context: ./server
    ports:
      - 8000:8000
    volumes:
      - ./server:/api
    
  pyapi:
    build:
      context: ./pyapi
    ports:
      - 8080:8080
    volumes:
      - ./pyapi:/pyapi
  
  postgres:
    image: postgres:15
    container_name: postgres_db
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
    volumes:
      - $PWD/docker/db/init:/docker-entrypoint-initdb.d
  
# sqlite3:
#     image: nouchka/sqlite3:latest
#     container_name: sqlite3_container
#     stdin_open: true
#     tty: true
#     volumes:
#       #Modify following line
#       - path-to/your/databases/sqlite3:/root/db/
#     ports:
#       - '9000:9000' # expose ports - HOST:CONTAINER
#     restart: unless-stopped