version: '3'

services:
  client:
    build:
      context: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front:/app
    command: yarn run dev

  server:
    build:
      context: ./server
    ports:
      - 8000:8000
    volumes:
      - ./server:/api
  
  db:
    image: postgres:10-alpine
    container_name: postgres_db
    ports: 
      - "5431:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_HOST: ${DATABASE_HOST}
    volumes:
      - $PWD/docker/db/init:/docker-entrypoint-initdb.d
      